; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30137.0 

	TITLE	C:\Users\romra\Documents\Cours\JV\Intelligence artificielle pour les jeux vidéo\Mini Projet\VS2015\Buckland_Chapter7 to 10_Raven\Debug\Goal_SayPhrase.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
