; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30133.0 

	TITLE	C:\Users\louis\Desktop\CANADA\Cours\Intelligence artificielle pour le jeu vidéo\Mini Projet\raven_VS2015\UQAC_mini_projet_IA\VS2015\Buckland_Chapter7 to 10_Raven\Debug\Goal_SayPhrase.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
